version: "3.8"

services:
  client:
    build:
      context: ./client
      target: development
    ports:
      - 3007:3007
    volumes:
      - ./client/src:/source/src
      - /source/node_modules
    depends_on:
      - server
  server:
    build:
      args:
      - NODE_ENV=development
      context: ./server
    command: npm run start
    restart: always
    environment:
      - DATABASE_PORT=3306
      - DATABASE_DB=tasks
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=db
      - NODE_ENV=development
    ports:
      - 5008:5008
      - 7800:7800
      - 7801:7801
    secrets:
      - db-password
    volumes:
      - ./server/src:/source/src:ro
      - ./server/package.json:/source/package.json
      - ./server/package-lock.json:/source/package-lock.json
      - server:/opt/app/node_modules
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=tasks
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - MYSQL_TCP_PORT=3306
  nginx:
    depends_on:
      - server
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    links:
      - "server"
      - "client"
volumes:
  server:
  db-data:
secrets:
  db-password:
    file: vault/db-password.txt
